### ISSUE TITLE
Expand Makefile to chipKIT MPIDE

### ISSUE THREAD

**Issue by rei-vilo** [turicas/arduinoMakefile#9]
MPIDE is derived from Arduino 0022 and deals with both Arduino and chipKIT platforms.

Expanding the Makefile to chipKIT would be great.

**Comment by turicas** [comment]
@rei-vilo, unfortunately I don't have chipKIT for testing it. Do you have one? Can you help with this issue?

**Comment by rei-vilo** [comment]
@turicas, sure! I could since I own a chipKIT UNO32 board. 

How is going [issue #4 External Libraries Not Compiled](https://github.com/turicas/arduinoMakefile/issues/4)? That's important because chipKIT uses specific libraries.

Three big challenges ahead:
- I hardly know much about Makefile works — tell me the data you need!
- templates have changed from Xcode 3 to Xcode 4 — I've found [this](http://dl.dropbox.com/u/1194636/AVR_Xcode4_template.zip)
- identify the Arduino corresponding references on the chipKIT platform.
